spring.application.name=auth-service
# This sets the port number where your Spring Boot app will run
# http://localhost:8080
server.port=8080
# JDBC URL to connect to PostgreSQL
# Format: jdbc:postgresql://<host>:<port>/<database_name>
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_auth_db
# Database username (default user created by PostgreSQL)
spring.datasource.username=${DB_USERNAME:postgres}
# Database password for the above user
spring.datasource.password=${DB_PASSWORD:}
# Controls how Hibernate handles database tables
# update = automatically creates/updates tables based on entities
# create = drops and recreates tables on every restart (DANGEROUS)
# none   = does nothing (production use)
spring.jpa.hibernate.ddl-auto=update
# Shows SQL queries in the console
spring.jpa.show-sql=true
# Formats SQL queries to make them readable in logs
spring.jpa.properties.hibernate.format_sql=true

# ================= JWT CONFIG =================
jwt.secret=${JWT_SECRET:change-me-in-local-env}
jwt.expiration=3600000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always



